version: '3'

services:
  ada-postgres:
    container_name: ada-postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Postgres2022'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./BACK/db.sql:/docker-entrypoint-initdb.d/db.sql

  ada-back:
    build: 
        context: ./BACK
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: ada-back
    volumes:
      - ./BACK:/app/back
      - /app/back/node_modules
    depends_on:
      - ada-postgres

  ada-front:
    container_name: ada-front
    build: 
        context: ./FRONT
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./FRONT:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true  
    depends_on:
      - ada-back

volumes:
  pgdata: